Write a program for hidden Markov model that calculates most probable path based upon the given observation. The program should take as input a sequence of probable observations. The graph size should be parameterized, and the weights of the graphs should be generated using a random number generator.

In [1]:
import random
import numpy as np

In [2]:
graph_size=4

In [3]:
#generating random numbers whose sum is 1.
x=np.random.dirichlet(np.ones(graph_size))

In [4]:
x

array([0.12099903, 0.10231903, 0.05827532, 0.71840662])

In [5]:
sum(x)

0.9999999999999999

In [6]:
#transition_probabilities
transition_probabilities=[]
for i in range(graph_size):
    transition_probabilities.append(np.random.dirichlet(np.ones(graph_size)))

In [7]:
transition_probabilities

[array([0.04805768, 0.11146709, 0.11747627, 0.72299897]),
 array([0.1266807 , 0.58392683, 0.26439735, 0.02499512]),
 array([0.26604173, 0.65620153, 0.06314786, 0.01460888]),
 array([0.37414908, 0.51908903, 0.03866065, 0.06810125])]

In [8]:
#Initial Probabilities
initial_probabilities=np.random.dirichlet(np.ones(graph_size))

In [9]:
initial_probabilities

array([0.42918834, 0.10699867, 0.28235414, 0.18145886])

In [10]:
#User Input
max_observation=3

In [11]:
#Emission Probabilities
emission_probabilities=[]
for i in range(graph_size):
    emission_probabilities.append(np.random.dirichlet(np.ones(max_observation)))


In [12]:
emission_probabilities

[array([0.51081086, 0.02603277, 0.46315637]),
 array([0.1150615 , 0.20183773, 0.68310076]),
 array([0.38264588, 0.27249543, 0.3448587 ]),
 array([0.58831904, 0.22849965, 0.18318131])]

In [13]:
#User Input
output_sequence='ABCA'

In [14]:
output_seq_int=[]
for i in output_sequence:
    output_seq_int.append(ord(i)-65)

In [15]:
output_seq_int

[0, 1, 2, 0]

In [16]:
sequence_list=[]
for i in range(graph_size):
    sequence_list.append(i)    

In [17]:
sequence_list

[0, 1, 2, 3]

In [18]:
def possible_path(past_sequence):
    seq_list=[]
    for i in range(len(past_sequence)):
        for j in range(graph_size):
            seq_list.append(str(past_sequence[i]) + str(j))
    return seq_list
    

In [19]:
possible_path(sequence_list)

['00',
 '01',
 '02',
 '03',
 '10',
 '11',
 '12',
 '13',
 '20',
 '21',
 '22',
 '23',
 '30',
 '31',
 '32',
 '33']

In [20]:
for i in range(len(output_seq_int)-1):
    new_chain=possible_path(sequence_list)
    sequence_list=new_chain

In [21]:
sequence_list

['0000',
 '0001',
 '0002',
 '0003',
 '0010',
 '0011',
 '0012',
 '0013',
 '0020',
 '0021',
 '0022',
 '0023',
 '0030',
 '0031',
 '0032',
 '0033',
 '0100',
 '0101',
 '0102',
 '0103',
 '0110',
 '0111',
 '0112',
 '0113',
 '0120',
 '0121',
 '0122',
 '0123',
 '0130',
 '0131',
 '0132',
 '0133',
 '0200',
 '0201',
 '0202',
 '0203',
 '0210',
 '0211',
 '0212',
 '0213',
 '0220',
 '0221',
 '0222',
 '0223',
 '0230',
 '0231',
 '0232',
 '0233',
 '0300',
 '0301',
 '0302',
 '0303',
 '0310',
 '0311',
 '0312',
 '0313',
 '0320',
 '0321',
 '0322',
 '0323',
 '0330',
 '0331',
 '0332',
 '0333',
 '1000',
 '1001',
 '1002',
 '1003',
 '1010',
 '1011',
 '1012',
 '1013',
 '1020',
 '1021',
 '1022',
 '1023',
 '1030',
 '1031',
 '1032',
 '1033',
 '1100',
 '1101',
 '1102',
 '1103',
 '1110',
 '1111',
 '1112',
 '1113',
 '1120',
 '1121',
 '1122',
 '1123',
 '1130',
 '1131',
 '1132',
 '1133',
 '1200',
 '1201',
 '1202',
 '1203',
 '1210',
 '1211',
 '1212',
 '1213',
 '1220',
 '1221',
 '1222',
 '1223',
 '1230',
 '1231',
 '1232',
 

In [22]:
prob_seq=[]
for i in range(len(sequence_list)):
    initial_state=int(sequence_list[i][0])
    first_obs=output_seq_int[0]
    i_prob= initial_probabilities[initial_state] * emission_probabilities[initial_state][first_obs]
     
    for j in range(1, len(output_seq_int)):
        next_state=int(sequence_list[i][j])
        prob = i_prob * transition_probabilities[initial_state][next_state] * emission_probabilities[next_state][output_seq_int[j]]
        initial_state=next_state
        i_prob = prob
       
    prob_seq.append(prob)           

In [23]:
len(prob_seq)

256

In [24]:
prob_seq

[1.4986649727690886e-07,
 7.829938524778505e-08,
 2.744282563341249e-07,
 2.5967625173592937e-06,
 1.3514289886689966e-06,
 1.4031727153685046e-06,
 2.1128894593887196e-06,
 3.0710775702407545e-07,
 1.5100538563842843e-06,
 8.389765823179184e-07,
 2.6849626542080396e-07,
 9.550195577300513e-08,
 6.942483561085082e-06,
 2.1696114345524977e-06,
 5.373734723508159e-07,
 1.4553854450194008e-06,
 7.104246982529047e-06,
 3.711691281825692e-06,
 1.3008952283578901e-05,
 0.00012309650664756502,
 0.000127312436714256,
 0.00013218699541177139,
 0.0001990464225927079,
 2.8931329140047833e-05,
 6.111744749985568e-05,
 3.39564757949764e-05,
 1.0867033871927857e-05,
 3.865316288828311e-06,
 4.31616693550725e-06,
 1.3488552121613272e-06,
 3.3408701554300833e-07,
 9.048183522424418e-07,
 2.12284214615475e-05,
 1.1091020210800379e-05,
 3.8872455100183385e-05,
 0.0003678285017377645,
 0.00020356822116011794,
 0.00021136247338404598,
 0.0003182684050453449,
 4.626020332998572e-05,
 2.0769551792307878e-05

In [25]:
def max_val(prob_seq):
    maxval=prob_seq[0]
    maxid=0
    for i in range(len(prob_seq)):
        if  prob_seq[i] > maxval:
            maxval=prob_seq[i]
            maxid=i
    return maxid   

In [26]:
max_val(prob_seq)

51

In [27]:
#Maximum Probability
prob_seq[max_val(prob_seq)]

0.00266964889066107

In [28]:
#Maximum probabilities Path 
sequence_list[max_val(prob_seq)]

'0303'